- name: Demo on using variables  
  hosts: all  
  vars:
    URL: play.google.com                     # Global Variable; All tasks can inherit this value 
  tasks:
    - name: Printing the URL Task  
      ansible.builtin.debug:
        msg: The value of url is {{URL}}  

    - name: Printing the URL from the Task
      ansible.builtin.debug:
        msg: The value of url is {{URL}}  
      vars:
        URL: task.google.com                 # Task / Local Level Variable ; The scope of is it only this task 


# $URL is bash is equivalent to {{URL}} in YAML 