- name: Demo on using variables  
  hosts: all  
  vars:
    URL: play.google.com                     # Global Variable; All tasks can inherit this value 
  tasks:
    - name: Printing the URL Task  
      ansible.builtin.debug:
        msg: The value of url is {{URL}}  

    - name: Printing the URL from the Task
      ansible.builtin.debug:
        msg: The value of url is {{URL}}  
      vars:
        URL: task.google.com                 # Task / Local Level Variable ; The scope of is it only this task 

    - name: Printing the URL
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: task.google.com                 # Task / Local Level Variable ; The scope of is it only this task 

    - name: Printing the value supplied from command line  
      ansible.builtin.debug:
        msg: "{{CMD_URL}}"



# $URL is bash is equivalent to {{URL}} in YAML 

# Local Variables > Global Variables


# When to specifically use Quites ? 
# When you're printing only the variable then enclose them in the Double Quotes.
