# When to use shell module; Whenever you want to execute or do something where the appropriate module is not availabe then only prefer using SHELL Module.
- name: Demo on using variables  
  hosts: all                   
  tasks:
  - name: Demo on using Shell Module 
    ansible.builtin.shell: uptime