- name: Creating a Roboshop User Account 
  ansible.builtin.user:
    name: "{{APPUSER}}" 
    comment: Roboshop User Account
  register: APPUSERINFO  

# - name: Debugging 
#   ansible.builtin.debug:
#     msg: "{{APPUSERINFO}}"
