# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "ws"
    static_configs:
      - targets: ["172.31.6.76:9100"]

# I have hardcoded telling to monitor server -x and server -y by giving the IP Address of the servers.
# What if if your servers comes up and destroys dynamically.

# I want to monitor the nodes dynamically 
# 1) Give a network range to be monitored 
# 2) Since the machines are already on AWS, we can let our Premetheus Server Query the nodes and fetch the information.
#    Monitor only the nodes that are having label as  ( prometheus-monitor : yes )